### ISSUE TITLE
Curious about figure 1.f for the true value and the estimation

### ISSUE THREAD

**Issue by ReinholdM** [sfujim/BCQ#10]
Hi, I think BCQ addresses the extrapolation error very well. And I'm curious about how to plot the figure 1.f as the paper show based on the collected offline batch. Great thanks for you reply

**Comment by sfujim** [comment]
I believe 1.f was plotted via training DDPG on a dataset of transitions collected by "expert" policies, and then plotting the average output of the critic on state-action pairs in that dataset. I don't have code for this, but it could be obtained by plotting current_Q (ideally on a larger batch size, every X time steps).
