### ISSUE TITLE
Discrete Environment other than Atari

### ISSUE THREAD

**Issue by CaralHsi** [sfujim/BCQ#4]
Hi,
I am very interested in your paper, especially for the discrete one. However, I found it hard to train an Atari game on my laptop. Instead of Atari, I want to try some naive states other than pixels. I noticed that you implemented the fully connected layers for non-Atari environments. Could you please give some advice on the environment?

**Comment by sfujim** [comment]
Hi, sorry for the super late reply, I completely missed this. The code is set up so that it will default to the fully connected layers for the non-Atari environments. So simply changing the environment with the --env argument should be enough to run non-Atari environments.
