### ISSUE TITLE
Training BCQ while evaluating policy with environment?

### ISSUE THREAD

**Issue by HYDesmondLiu** [sfujim/BCQ#7]
Hi,
    Thanks for sharing the source code. I am trying to implement your code on my environment: I have my **_{action, state, next_state, reward, not_done, ptr}_** npy files all prepared in the **_./buffer_** folder. Then I start to train my BCQ, however I saw that `train_BCQ` in `main.py` in the "while` training_iters < args.max_timesteps:` loop is calling` eval_policy`, I thought batch RL does not interact with environment. If so how do I set the  `env.step` in my environment?

**Comment by sfujim** [comment]
Issue addressed over email.

**Comment by isofun** [comment]
> Hi, Thanks for sharing the source code. I am trying to implement your code on my environment: I have my **_{action, state, next_state, reward, not_done, ptr}_** npy files all prepared in the **_./buffer_** folder. Then I start to train my BCQ, however I saw that `train_BCQ` in `main.py` in the "while` training_iters < args.max_timesteps:` loop is calling` eval_policy`, I thought batch RL does not interact with environment. If so how do I set the `env.step` in my environment?

I also have the same  question, can you share the answer?

**Comment by HYDesmondLiu** [comment]
The BRL models are just being evaluated in the environments. There are no new transitions stored in the buffers.
